// Auto-generated by Supabase — no editar manualmente
// Regenerar con: supabase gen types typescript --project-id ufmffyytvjrpibbkjdjn

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      appointments: {
        Row: {
          client_id: string | null
          created_at: string
          date: string
          end_time: string
          id: string
          notes: string | null
          payment_status: string
          service_id: string | null
          start_time: string
          status: string
        }
        Insert: {
          client_id?: string | null
          created_at?: string
          date: string
          end_time: string
          id?: string
          notes?: string | null
          payment_status?: string
          service_id?: string | null
          start_time: string
          status?: string
        }
        Update: {
          client_id?: string | null
          created_at?: string
          date?: string
          end_time?: string
          id?: string
          notes?: string | null
          payment_status?: string
          service_id?: string | null
          start_time?: string
          status?: string
        }
        Relationships: [
          { foreignKeyName: "appointments_client_id_fkey"; columns: ["client_id"]; isOneToOne: false; referencedRelation: "clients"; referencedColumns: ["id"] },
          { foreignKeyName: "appointments_service_id_fkey"; columns: ["service_id"]; isOneToOne: false; referencedRelation: "services"; referencedColumns: ["id"] },
        ]
      }
      client_notes: {
        Row: {
          appointment_id: string | null
          client_id: string
          content: string
          created_at: string
          id: string
        }
        Insert: {
          appointment_id?: string | null
          client_id: string
          content: string
          created_at?: string
          id?: string
        }
        Update: {
          appointment_id?: string | null
          client_id?: string
          content?: string
          created_at?: string
          id?: string
        }
        Relationships: [
          { foreignKeyName: "client_notes_appointment_id_fkey"; columns: ["appointment_id"]; isOneToOne: false; referencedRelation: "appointments"; referencedColumns: ["id"] },
          { foreignKeyName: "client_notes_client_id_fkey"; columns: ["client_id"]; isOneToOne: false; referencedRelation: "clients"; referencedColumns: ["id"] },
        ]
      }
      clients: {
        Row: {
          allergies: string | null
          birthdate: string | null
          created_at: string
          email: string | null
          id: string
          name: string
          notes: string | null
          phone: string | null
          preferences: Json
        }
        Insert: {
          allergies?: string | null
          birthdate?: string | null
          created_at?: string
          email?: string | null
          id?: string
          name: string
          notes?: string | null
          phone?: string | null
          preferences?: Json
        }
        Update: {
          allergies?: string | null
          birthdate?: string | null
          created_at?: string
          email?: string | null
          id?: string
          name?: string
          notes?: string | null
          phone?: string | null
          preferences?: Json
        }
        Relationships: []
      }
      payments: {
        Row: {
          amount: number
          appointment_id: string
          created_at: string
          gateway_id: string | null
          id: string
          method: string
          proof_url: string | null
          status: string
        }
        Insert: {
          amount: number
          appointment_id: string
          created_at?: string
          gateway_id?: string | null
          id?: string
          method: string
          proof_url?: string | null
          status?: string
        }
        Update: {
          amount?: number
          appointment_id?: string
          created_at?: string
          gateway_id?: string | null
          id?: string
          method?: string
          proof_url?: string | null
          status?: string
        }
        Relationships: [
          { foreignKeyName: "payments_appointment_id_fkey"; columns: ["appointment_id"]; isOneToOne: false; referencedRelation: "appointments"; referencedColumns: ["id"] },
        ]
      }
      services: {
        Row: {
          category: string
          created_at: string
          description: string | null
          duration_minutes: number
          id: string
          is_active: boolean
          name: string
          price: number
        }
        Insert: {
          category: string
          created_at?: string
          description?: string | null
          duration_minutes: number
          id?: string
          is_active?: boolean
          name: string
          price: number
        }
        Update: {
          category?: string
          created_at?: string
          description?: string | null
          duration_minutes?: number
          id?: string
          is_active?: boolean
          name?: string
          price?: number
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      get_available_slots: {
        Args: { p_date: string; p_duration_mins: number }
        Returns: { slot_end: string; slot_start: string }[]
      }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

// ── Custom domain types ───────────────────────────────────────────
export type AppointmentStatus =
  | 'pending' | 'confirmed' | 'in_progress'
  | 'completed' | 'cancelled' | 'no_show'

export type PaymentStatus = 'unpaid' | 'pending_verification' | 'paid'
export type PaymentMethod = 'cash' | 'transfer' | 'online'
export type PaymentVerificationStatus = 'pending' | 'verified' | 'rejected'
export type ServiceCategory =
  | 'manicure' | 'pedicure' | 'nail_art' | 'gel' | 'acrilico' | 'otros'
